
framework = "next"
origin = "http://localhost:5000"
inline.array = [1234, 4, 5, 6]

[macros]
react-relay = { "graphql" = "node_modules/bun-macro-relay/bun-macro-relay.tsx" }

[bundle.packages]
"@emotion/react" = true

[dev]
foo = 123
"foo.bar" = "baz"
"abba.baba" = "baba"
dabba = -123
doo = 123.456
one.two.three = 4

[[array]]
entry_one = "one"
entry_two = "two"

[[array]]
entry_one = "three"

[[array.nested]]
entry_one = "four"
