name: bun-test
on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        default: canary
jobs:
  bun:
    name: Bun
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/bun-test
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v0.1.8
        with:
          bun-version: ${{ github.event.inputs.release || 'canary' }}
      - id: setup-dependencies
        name: Setup Dependencies
        run: bun install
      - id: test
        name: Test
        run: bun run test
