name: TypeScript Types
on:
  push:
    paths:
      - packages/bun-types/**/*
  pull_request:
    paths:
      - packages/bun-types/**/*

jobs:
  tests:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/bun-types

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install bun
        uses: xhyrom/setup-bun@v0.1.8
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate package
        run: bun run build

      - name: ESLint
        run: bun run lint

      - name: Tests
        run: bun run test
