name: CI workflow for bun-framework-next
on:
  push:
    branches: [main, bun-framework-next-actions]
  pull_request:
    branches: [main]

jobs:
  build:
    name: lint, test and build on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ["14.x"]
        os: [macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.21.0

      - name: Install dependencies
        run: cd packages/bun-framework-next && pnpm install

      - name: Test bun-framework-next
        run: cd packages/bun-framework-next && pnpm check
