name: C++ Linter comment

permissions:
  actions: read
  pull-requests: write

on:
  pull_request:

env:
  LLVM_VERSION_MAJOR: "19"

jobs:
  comment-lint:
    if: ${{ github.repository_owner == 'oven-sh' }}
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun

      - name: Run clang-tidy
        id: env
        shell: bash
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc > /dev/null
          echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-${{ env.LLVM_VERSION_MAJOR }} main" | sudo tee /etc/apt/sources.list.d/llvm.list > /dev/null
          sudo apt-get update -qq
          sudo apt-get install -y -qq --no-install-recommends --no-install-suggests -o=Dpkg::Use-Pty=0 clang-format-${{ env.LLVM_VERSION_MAJOR }}

          # Copy to outputs
          {
            echo 'text_output<<EOF'
            bun run clang-tidy:check
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Find Comment
        id: comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          comment-author: github-actions[bot]
          body-includes: <!-- generated-comment lint-cpp-workflow=${{ github.workflow }} -->
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            @${{ github.actor }}, `clang-tidy` had something to share with you about your code:

            ```cpp
            ${{ steps.env.outputs.text_output }}
            ```

            Commit: ${{ github.event.workflow_run.head_sha || github.sha }}

            <!-- generated-comment lint-cpp-workflow=${{ github.workflow }} -->
          edit-mode: replace
