name: prettier-format

permissions:
  contents: write

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/prettier-format.yml"
      - "package.json"
      - "scripts/**"
      - "**.yml"
      - "**.json"
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "**.mjs"
      - "**.cjs"

env:
  BUN_VERSION: "1.1.27"

jobs:
  prettier-format:
    name: prettier-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Setup Dependencies
        run: |
          bun install
      - name: Format
        env:
          ENABLE_CCACHE: OFF
          SKIP_LLVM: ON
        run: |
          bun run prettier:diff
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "`bun run prettier:extra`"
