name: zig-format

permissions:
  contents: write

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/zig-format.yml"
      - "package.json"
      - "scripts/**"
      - "cmake/**"
      - "src/**/*.zig"

env:
  BUN_VERSION: "1.1.27"

jobs:
  zig-format:
    name: zig-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            package.json
            scripts
            cmake
            src
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Zig Format
        run: |
          bun run zig-format -DENABLE_CCACHE=OFF -DSKIP_LLVM=ON
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "`bun run zig-format`"
